config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  resources :green_kub_boxes
  resources :sensor_actuator_infos
  resources :sensors
  resources :actuators
  resources :sensor_types
  resources :actuator_types
  resources :models
  devise_for :users

end

app/controllers/actuator_types_controller.rb
class ActuatorTypesController < ApplicationController
  before_action :set_actuator_type, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  # GET /actuator_types
  # GET /actuator_types.json
  def index
    @actuator_types = ActuatorType.all
  end

  # GET /actuator_types/1
  # GET /actuator_types/1.json
  def show
  end

  # GET /actuator_types/new
  def new
    @actuator_type = ActuatorType.new
  end

  # GET /actuator_types/1/edit
  def edit
  end

  # POST /actuator_types
  # POST /actuator_types.json
  def create
    @actuator_type = ActuatorType.new(actuator_type_params)

    respond_to do |format|
      if @actuator_type.save
        format.html { redirect_to @actuator_type, notice: 'Actuator type was successfully created.' }
        format.json { render :show, status: :created, location: @actuator_type }
      else
        format.html { render :new }
        format.json { render json: @actuator_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actuator_types/1
  # PATCH/PUT /actuator_types/1.json
  def update
    respond_to do |format|
      if @actuator_type.update(actuator_type_params)
        format.html { redirect_to @actuator_type, notice: 'Actuator type was successfully updated.' }
        format.json { render :show, status: :ok, location: @actuator_type }
      else
        format.html { render :edit }
        format.json { render json: @actuator_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actuator_types/1
  # DELETE /actuator_types/1.json
  def destroy
    @actuator_type.destroy
    respond_to do |format|
      format.html { redirect_to actuator_types_url, notice: 'Actuator type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actuator_type
      @actuator_type = ActuatorType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actuator_type_params
      params.require(:actuator_type).permit(:name, :caracteristics)
    end
end

app/views/actuator_types/index.html.erb
<%- model_class = ActuatorType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <% if(current_user.isAdmin) %>
        <th><%= model_class.human_attribute_name(:id) %></th>
      <% end %>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:caracteristics) %></th>
      <% if(current_user.isAdmin) %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @actuator_types.each do |actuator_type| %>
      <tr>
        <% if(current_user.isAdmin) %>
            <td><%= link_to actuator_type.id, actuator_type_path(actuator_type) %></td>
        <% end %>
        <td><%= actuator_type.name %></td>
        <td><%= actuator_type.caracteristics %></td>
        <% if(current_user.isAdmin) %>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_actuator_type_path(actuator_type), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          actuator_type_path(actuator_type),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if(current_user.isAdmin) %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
            new_actuator_type_path,
            :class => 'btn btn-primary' %>
<% end %>