config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  resources :green_kub_boxes
  resources :sensor_actuator_infos
  resources :sensors
  resources :actuators
  resources :sensor_types
  resources :actuator_types
  resources :models
  devise_for :users

end

app/controllers/sensor_types_controller.rb
class SensorTypesController < ApplicationController
  before_action :set_sensor_type, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  # GET /sensor_types
  # GET /sensor_types.json
  def index
    @sensor_types = SensorType.all
  end

  # GET /sensor_types/1
  # GET /sensor_types/1.json
  def show
  end

  # GET /sensor_types/new
  def new
    @sensor_type = SensorType.new
  end

  # GET /sensor_types/1/edit
  def edit
  end

  # POST /sensor_types
  # POST /sensor_types.json
  def create
    @sensor_type = SensorType.new(sensor_type_params)

    respond_to do |format|
      if @sensor_type.save
        format.html { redirect_to @sensor_type, notice: 'Sensor type was successfully created.' }
        format.json { render :show, status: :created, location: @sensor_type }
      else
        format.html { render :new }
        format.json { render json: @sensor_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensor_types/1
  # PATCH/PUT /sensor_types/1.json
  def update
    respond_to do |format|
      if @sensor_type.update(sensor_type_params)
        format.html { redirect_to @sensor_type, notice: 'Sensor type was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor_type }
      else
        format.html { render :edit }
        format.json { render json: @sensor_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensor_types/1
  # DELETE /sensor_types/1.json
  def destroy
    @sensor_type.destroy
    respond_to do |format|
      format.html { redirect_to sensor_types_url, notice: 'Sensor type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor_type
      @sensor_type = SensorType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_type_params
      params.require(:sensor_type).permit(:name, :caracteristics, :unit)
    end
end

app/views/sensor_types/index.html.erb
<%- model_class = SensorType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <% if(current_user.isAdmin) %>
        <th><%= model_class.human_attribute_name(:id) %></th>
      <% end %>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:caracteristics) %></th>
      <th><%= model_class.human_attribute_name(:unit) %></th>
      <% if(current_user.isAdmin) %>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @sensor_types.each do |sensor_type| %>
      <tr>
        <% if(current_user.isAdmin) %>
            <td><%= link_to sensor_type.id, sensor_type_path(sensor_type) %></td>
        <% end %>
        <td><%= sensor_type.name %></td>
        <td><%= sensor_type.caracteristics %></td>
        <td><%= sensor_type.unit %></td>
        <% if(current_user.isAdmin) %>
            <td><%=l sensor_type.created_at %></td>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_sensor_type_path(sensor_type), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          sensor_type_path(sensor_type),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if(current_user.isAdmin) %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_sensor_type_path,
                :class => 'btn btn-primary' %>
<% end %>