config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  resources :green_kub_boxes
  resources :sensor_actuator_infos
  resources :sensors
  resources :actuators
  resources :sensor_types
  resources :actuator_types
  resources :models
  devise_for :users

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed " data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%=link_to image_tag("logo_greenkub.png",:class=>"navbar-brand"), root_path,id: "logo"  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">-->
      <div class="collapse navbar-collapse ">


        <div id="navbar-example">
          <ul class="nav navbar-nav navbar-right" >
            <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
            <ul class="nav nav-tabs nav-justified">-->
      <!--  <li class="<%= 'active' if params[:controller] == 'sensors' %>"><%= link_to "Sensors",   sensors_path,class:"navbar-right" %></li>

        <li class="<%= 'active' if params[:controller] == 'actuators' %>"><%= link_to "Actuators",   actuators_path,class:"navbar-right" %></li>
        <li class="<%= 'active' if params[:controller] == 'sensor_actuator_infos' %>"><%= link_to "Info Sensors", sensor_actuator_infos_path,class:"navbar-right" %></li>
        <li class="<%= 'active' if params[:controller] == 'sensor_types' %>"><%= link_to "Type Sensors", sensor_types_path ,class:"navbar-right"%></li>
        <li class="<%= 'active' if params[:controller] == 'actuator_types' %>"><%= link_to "Type Actuators", actuator_types_path,class:"navbar-right" %></li>
        <li><%= link_to "Session",  :anchor => "session", :id => "news" %> </li>-->

            <!--<li><%= link_to "Comment##{session}" %></li>-->
            <li class="current">   <%= link_to "Home", "#home" , class:"page-scroll"%></li>
            <li>   <%= link_to "About", "#about", class:"page-scroll"%></li>
            <li>   <%= link_to "Team", "#team", class:"page-scroll" %></li>
            <li>   <%= link_to "Session1", "#session1", class:"page-scroll"%></li>
            <li> <ul class="nav navbar-nav navbar-right">
              <li><a href="#">Link</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Actuators",   actuators_path %></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                </ul>
              </li>
            </ul>
            </li>

            </ul>
          </div>
</div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenKub - Farm Yourself !</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <![endif]-->
  <%= render 'layouts/shim' %>
</head>
<!--<body>-->

<body data-spy="scroll" data-target="#navbar-example">
<!--</body>-->
<%= render 'layouts/header' %>
<div class="container-fluid">

  <% if current_user %>
      Signed in as <strong><%= current_user.email %></strong>!
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
      <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %><br>
      <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %><br>
      <%= link_to "Sign in", new_user_session_path, id: "sign_in" %>
  <% end %>
</div>

<div class="container">

<%= yield %>

  <%= render 'layouts/footer' %>

</div>

</body>
</html>